spring.application.name=Security

spring.docker.compose.enabled=false

spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

# Define um usuário e senha fixos para o Spring Security
spring.security.user.name=caio
spring.security.user.password=123

# Libera o console do H2 para não pedir a senha do Spring (Opcional mas ajuda)
spring.h2.console.settings.web-allow-others=true
